# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e972c28734a722a7ee767d703a5680bb3e6806e2f6ba47a84a6c6499d6c421aba627b333b923e64f3549600f82558817be7b49ca72b2b70250e2c185f0253b

test:
  secret_key_base: 7da4134205da4897294d938fe692008f80b78283cef6bbc519bca13a08f2a664c4676549b6dac25edfbc1ab295ff4b7899ab9cdafa0504df9d703745d424a52c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
